### ISSUE TITLE
Is this compatible with linux?

### ISSUE THREAD

**Issue by Rubiooo04** [aaronzygala/TikTokPlaysPokemon#1]
I'm trying to use this on a raspberry pi but I don't know if it works with linux or how to get it to work on linux

**Comment by aaronzygala** [comment]
I have only tested this on Windows. I believe a major package that I am using (PyGetWindow) is not supported on Linux systems.

**Comment by aaronzygala** [comment]
I made this for a specific TikTok livestreamer so his chat can input commands into a gameboy emulator, so a lot of the code is tied to his specific use case. If you would like to run it as well, I can update it to be used by other streamers as well. First I'd need to use an alternative to PyGetWindow that is compatible with linux.
